# The version of the docker compose syntax.
version: "3.9"
services:
# The name of our service
  app:
    build: 
      # buld our context from the root directory
      context: .
      # if running through this docker compose file (only in development), create a build argument called DEV and set it to true.
      args:
        - DEV=true
      # map port 8000 from our local machine to the port oninside the docker container.
    ports:
      - "8000:8000"
      # map directories from our project to the container. in order to automatically sync the code in our project to the code in the container.
    volumes:
      - ./app:/app
      # The command that used to run the service(usually we override the command but this is the default command)
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme

    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:   